# Generated by Django 5.2 on 2025-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='encryptedphoto',
            name='file',
            field=models.FileField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='encryptedphoto',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
