# Generated by Django 5.2 on 2025-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_encryptedphoto_image_encryptedphoto_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedphoto',
            name='file',
            field=models.FileField(default='', upload_to='photos/'),
        ),
    ]
